name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --verbose
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
